[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: marks tests as ui (deselect with '-m "not ui"')
    api: marks tests as api (deselect with '-m "not api"')